set number
set smartindent
set autoindent
set ruler
syntax on
colorscheme molokai 

inoremap ( ()<left>
inoremap [ []<left>
inoremap ' '' <left>
inoremap " "" <left>

nnoremap ; :
vnoremap ; :

" Navigate between split pane
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
