source $VIM_CONF/vimrc_remap
source $VIM_CONF/vimrc_vimplug
source $VIM_CONF/vimrc_nerdtree
source $VIM_CONF/vimrc_gitgutter
source $VIM_CONF/vimrc_syntastic
source $VIM_CONF/vimrc_nerdcommenter
source $VIM_CONF/vimrc_ctrlp

" update stuff like git symbol in margin (default 4000 = 4s)
set updatetime=1000

set noswapfile

set smartindent
set autoindent

set ruler
set number
set relativenumber

syntax on
colorscheme molokai
