# EXPORTS
source ~/workspace/config/zsh/exports.zsh

# ZSH CONFIG
source $ZSH/oh-my-zsh.sh

# COLORS
source $ZSH_CONF/colors.zsh

# ALIAS
source $ZSH_CONF/alias.zsh

# COMMANDS
source $ZSH_CONF/commands.zsh
