# EXPORTS
source ~/workspace/config/zsh/exports.zsh

# ZSH CONFIG
source $ZSH/oh-my-zsh.sh

# COLORS
source $CONF_ZSH/colors.zsh

# ALIAS
source $CONF_ZSH/alias.zsh

# COMMANDS
source $CONF_ZSH/commands.zsh
