#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

# Font from neutonfoo/dotfiles
FONT="JetBrainsMono Nerd Font"

# Setting up the general bar appearance - CriticalElement floating style
bar=(
  height=58
  color=$TRANSPARENT
  shadow=off
  position=top
  sticky=on
  padding_left=0
  padding_right=0
  y_offset=-8
  margin=6
  blur_radius=0
  notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values - CriticalElement pill style
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:22.0"
  icon.color=0xffcf6679
  icon.padding_left=12
  icon.padding_right=4
  label.font="$FONT:Bold:14.0"
  label.color=$LABEL_COLOR
  label.padding_left=4
  label.padding_right=12
  background.color=$DARK_BG
  background.height=30
  background.corner_radius=10
  background.drawing=on
  background.border_width=3
  background.padding_left=8
  blur_radius=2
  y_offset=0
  popup.background.border_width=2
  popup.background.corner_radius=15
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left Side Items
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right Side Items (order matters, right-most first)
# source "$ITEM_DIR/settings.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/headset.sh"
source "$ITEM_DIR/network_down.sh"
source "$ITEM_DIR/network_up.sh"
source "$ITEM_DIR/ram.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/vpn.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/ethernet.sh"

# Forcing all item scripts to run (never do this in production)
sketchybar --update

echo "sketchybar configuration loaded..."
