#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="SF Pro"
PADDINGS=3

# Setting up the general bar appearance
bar=(
  height=39
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_left=10
  padding_right=10
  corner_radius=9
  y_offset=10
  margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left Side Items
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right Side Items (order matters, right-most first)
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this in production)
sketchybar --update

echo "sketchybar configuration loaded..."
